[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
fs_permissions = [
    { access = "read", path = "lib/foundry-chainlink-toolkit/out" },
]
remappings = [
    '@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/',
    '@chainlink/test=../../lib/chainlink-brownie-contracts/contracts/',
    '@solmate=lib/solmate/src/',
    '@solmateTest=../../lib/solmate/src/',
]

# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config
